### ISSUE TITLE
Help and Support

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/CubeSpinner#2]
This issue thread is intended for questions on how to get the machine working, as this is actually no trivial matter.
Please state the exact problem and what you have done so far. Also how the machine behaves and what the debug output on the display looks like. Uploading pictures and videos is highly recommended.

**Comment by fishfilms** [comment]
so i start program cubespinner i wait until color sensor white and push the button and it start scanning and i push the button again and it scans again I push the button again and the program ends

**Comment by c0pperdragon** [comment]
could do take (and post) a picture of what the display shows after the scan?

**Comment by fishfilms** [comment]
![ev3](https://user-images.githubusercontent.com/101213456/158255795-308766c4-b2ce-4e70-b592-18b6d0e9fad6.jpg)

**Comment by c0pperdragon** [comment]
This "calibration finished" should only appear when you are using two color sensors and only at the first scan attempt after starting the program.
To eliminate some unknowns, unplug the second color sensor (like I did on the youtube video) and try this. Then there is no calibration run and you get results directly. Also is probably less error-prone.

**Comment by fishfilms** [comment]
i dont have a seconde sensorcolor

**Comment by fishfilms** [comment]
update i changed the port of the colorsenso
![download](https://user-images.githubusercontent.com/101213456/158668145-64c7ad3a-4826-4ebb-ac08-ffc554221e4c.jpg)
r

**Comment by c0pperdragon** [comment]
This looks much more promising. Counting the various letters on the display shows that the scanning process detects 12 red and only 6 orange sides. It is a common problem that the machine has a very hard time to distinguish red and orange. There are some heuristics in place to compensate for this fact, but they don't always work.
As the other colors seem to be quite reliably detectable, you could actually try to modify your cube a bit to make red and orange look more different. Maybe stick some darker red paper on the red sides to darken them.
